# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Open Source Licensing
author: Operate First
copyright: "2022"
logo: logo.png
exclude_patterns: [_build, Thumbs.db, .DS_Store]
only_build_toc_file: false

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/operate-first/training
  path_to_book: courses/course-open_source_licensing
  branch: master

# Settings in the rendered HTML
html:
  favicon: "favicon-32x32.png"
  use_issues_button: true
  use_repository_button: true
